# Generated by Django 4.0.4 on 2022-08-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
