# Generated by Django 4.0.4 on 2022-08-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default='1111', max_length=20),
        ),
    ]
