# Generated by Django 4.0.4 on 2022-08-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_login_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='grade',
            field=models.CharField(default='IM', max_length=10),
        ),
    ]
