# Generated by Django 4.0.4 on 2022-08-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_login_email_login_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='telephone',
            field=models.IntegerField(default='01000000000'),
        ),
    ]
