# Generated by Django 4.0.4 on 2022-08-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_descript_login_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='description',
            new_name='descript',
        ),
        migrations.AlterField(
            model_name='login',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
