# Generated by Django 4.1 on 2022-09-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies_info',
            name='sub_description',
            field=models.TextField(default='aa'),
        ),
    ]
