# Generated by Django 4.0.4 on 2022-09-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_info_sub_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies_info',
            name='genre',
            field=models.CharField(choices=[('공포', '공포'), ('스릴러', '스릴러'), ('액션', '액션'), ('드라마', '드라마')], max_length=30),
        ),
    ]
