# Generated by Django 4.0.4 on 2022-10-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usermodel_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articlemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
            ],
        ),
    ]
