# Generated by Django 4.1 on 2022-09-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('variety', models.CharField(choices=[('Backjoon', 'Backjoon'), ('SWEA', 'SWEA'), ('Programmers', 'Programmers')], max_length=30)),
            ],
        ),
    ]
