# Generated by Django 4.0.4 on 2022-09-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_delete_personalmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='variety',
            field=models.CharField(choices=[('Backjoon', 'Backjoon'), ('SWEA', 'SWEA'), ('Programmers', 'Programmers')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
