# Generated by Django 4.0.4 on 2022-09-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='username',
            field=models.CharField(default='Please write', max_length=30),
        ),
    ]
