# Generated by Django 4.0.4 on 2022-09-18 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_articlemodel_variety'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='release_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
