# Generated by Django 4.0.4 on 2022-09-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_articlemodel_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='release_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
