# Generated by Django 4.0.4 on 2022-09-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_alter_articlemodel_release_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
