# Generated by Django 4.0.4 on 2022-09-19 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_articlemodel_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='CommentModel_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Please write', max_length=30)),
                ('comment', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.commentmodel')),
            ],
        ),
    ]
